// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/lame_mp3.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class LameMp3Bindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LameMp3Bindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LameMp3Bindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Creates a constant-bitrate encoder. Input and output sample rates are both
  /// `sample_rate` (LAME never resamples), which must be one of the MPEG rates:
  /// MPEG-1:   32000, 44100, 48000 Hz  (1152 samples per frame)
  /// MPEG-2:   16000, 22050, 24000 Hz  (576 samples per frame)
  /// MPEG-2.5:  8000, 11025, 12000 Hz  (576 samples per frame)
  /// `channels` is 1 (mono) or 2 (joint stereo, interleaved input).
  /// `bitrate_kbps` must be a Layer III bitrate that LAME supports at that rate:
  /// MPEG-1:   32 40 48 56 64 80 96 112 128 160 192 224 256 320
  /// MPEG-2:    8 16 24 32 40 48 56 64 80 96 112 128 144 160
  /// MPEG-2.5:  8 16 24 32 40 48 56 64
  /// (LAME would silently pick the nearest supported bitrate; this wrapper
  /// fails instead.) `quality` is LAME's algorithm quality, 0 (best, slowest) to 9
  /// (worst, fastest); 5 is a good default for speech.
  /// Returns an opaque handle, or NULL if any argument is invalid, allocation
  /// fails or LAME rejects the configuration. Release it with lame_mp3_close().
  ffi.Pointer<ffi.Void> lame_mp3_create(
    int sample_rate,
    int channels,
    int bitrate_kbps,
    int quality,
  ) {
    return _lame_mp3_create(sample_rate, channels, bitrate_kbps, quality);
  }

  late final _lame_mp3_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
            ffi.Int32,
          )
        >
      >('lame_mp3_create');
  late final _lame_mp3_create = _lame_mp3_createPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int, int, int, int)>();

  /// Encodes `samples_per_channel` 16-bit PCM samples per channel. For stereo
  /// encoders `pcm` holds 2 * samples_per_channel interleaved samples (L R L R
  /// ...); for mono encoders it holds samples_per_channel samples.
  /// Writes the MP3 bytes that became available to `out` (LAME buffers about
  /// one and a half frames internally, so this may be 0) and returns their
  /// count, or a negative LAME_MP3_ERROR_* code.
  /// `out_capacity` must be at least LAME_MP3_ENCODE_BUFFER_SIZE(samples).
  /// With samples_per_channel == 0 nothing is read or written and 0 is returned.
  int lame_mp3_encode(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Int16> pcm,
    int samples_per_channel,
    ffi.Pointer<ffi.Uint8> out,
    int out_capacity,
  ) {
    return _lame_mp3_encode(
      handle,
      pcm,
      samples_per_channel,
      out,
      out_capacity,
    );
  }

  late final _lame_mp3_encodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Int16>,
            ffi.Int32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('lame_mp3_encode');
  late final _lame_mp3_encode = _lame_mp3_encodePtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Int16>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// Encodes the buffered samples (zero-padding the last frame) and writes the
  /// final frames to `out`; call it once, after the last lame_mp3_encode().
  /// Returns the number of bytes written or a negative LAME_MP3_ERROR_* code.
  /// `out_capacity` must be at least LAME_MP3_FLUSH_BUFFER_SIZE.
  int lame_mp3_flush(
    ffi.Pointer<ffi.Void> handle,
    ffi.Pointer<ffi.Uint8> out,
    int out_capacity,
  ) {
    return _lame_mp3_flush(handle, out, out_capacity);
  }

  late final _lame_mp3_flushPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int32,
          )
        >
      >('lame_mp3_flush');
  late final _lame_mp3_flush = _lame_mp3_flushPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Frees the encoder. NULL is ignored; the handle must not be used afterwards.
  void lame_mp3_close(ffi.Pointer<ffi.Void> handle) {
    return _lame_mp3_close(handle);
  }

  late final _lame_mp3_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'lame_mp3_close',
      );
  late final _lame_mp3_close = _lame_mp3_closePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// LAME's version string, e.g. "4.0" (static storage, never NULL).
  ffi.Pointer<ffi.Char> lame_mp3_version() {
    return _lame_mp3_version();
  }

  late final _lame_mp3_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'lame_mp3_version',
      );
  late final _lame_mp3_version = _lame_mp3_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  late final addresses = _SymbolAddresses(this);
}

class _SymbolAddresses {
  final LameMp3Bindings _library;
  _SymbolAddresses(this._library);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
  get lame_mp3_close => _library._lame_mp3_closePtr;
}

const int LAME_MP3_FLUSH_BUFFER_SIZE = 7200;

const int LAME_MP3_ERROR_BUFFER_TOO_SMALL = -1;

const int LAME_MP3_ERROR_OUT_OF_MEMORY = -2;

const int LAME_MP3_ERROR_NOT_INITIALIZED = -3;

const int LAME_MP3_ERROR_PSYCHOACOUSTIC = -4;

const int LAME_MP3_ERROR_INVALID_ARGUMENT = -100;
