"""Writes the Android notification and media-control icons as vector drawables,
from Material Icons (Apache 2.0, the font that ships with the Flutter SDK:
bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf).

Usage: python3 tool/art/android_icons.py <MaterialIcons-Regular.otf> <res/drawable dir>
"""
import os
import sys

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ICONS = [
    # drawable name, glyph, what it is for
    ('ic_stat_playback', 'play_arrow_baseline', 'playback notification (status bar)'),
    ('ic_media_play', 'play_arrow_baseline', 'play button'),
    ('ic_media_pause', 'pause_baseline', 'pause button'),
    ('ic_media_rewind10', 'replay_10_baseline', 'back 10 seconds'),
    ('ic_media_forward10', 'forward_10_baseline', 'forward 10 seconds'),
    ('ic_media_stop', 'stop_baseline', 'stop recording'),
    ('ic_media_record', 'fiber_manual_record_baseline', 'resume recording'),
]

TEMPLATE = '''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by tool/art/android_icons.py from Material Icons (Apache 2.0): {what}. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="{em}"
    android:viewportHeight="{em}">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="{d}" />
</vector>
'''


def main():
    font = TTFont(sys.argv[1])
    out = sys.argv[2]
    em = font['head'].unitsPerEm
    gs = font.getGlyphSet()
    for name, glyph, what in ICONS:
        pen = SVGPathPen(gs, ntos=lambda v: ('%.1f' % v).rstrip('0').rstrip('.'))
        # font units have y up from the baseline; drawables have y down
        gs[glyph].draw(TransformPen(pen, (1, 0, 0, -1, 0, em)))
        with open(os.path.join(out, name + '.xml'), 'w') as fh:
            fh.write(TEMPLATE.format(what=what, em=em, d=pen.getCommands()))


if __name__ == '__main__':
    main()
