"""Extracts the icon outlines used by the app from open-licensed icon fonts and
writes them as SVG path data into lib/src/ui/icons/glyph_data.dart.

Sources (fetched from npm / the Flutter SDK, see THIRD_PARTY_NOTICES.md):
  * Font Awesome 4.7.0  (SIL OFL 1.1)   fonts/fontawesome-webfont.ttf
  * Ionicons 2.0.1      (MIT)           fonts/ionicons.ttf
  * Material Icons      (Apache 2.0)    MaterialIcons-Regular.otf

Each glyph is emitted in its own coordinate space with y pointing down and the
ink bounding box starting at (0, 0), so the Dart side can scale a glyph to the
exact ink size measured from the reference screenshots.

Usage: python3 tool/art/extract_glyphs.py --fa <fa.ttf> --ion <ionicons.ttf> \
          --material <MaterialIcons-Regular.otf> --out lib/src/ui/icons/glyph_data.dart
"""
import argparse

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

GLYPHS = [
    # name, font key, codepoint
    ('share', 'fa', 0xf1e0),          # fa-share-alt
    ('trash', 'fa', 0xf014),          # fa-trash-o
    ('floppy', 'fa', 0xf0c7),         # fa-floppy-o
    ('folderOpen', 'fa', 0xf07c),     # fa-folder-open
    ('star', 'fa', 0xf005),           # fa-star
    ('certificate', 'fa', 0xf0a3),    # fa-certificate
    ('mic', 'ion', 0xf460),           # ion-ios-mic-outline
    ('gear', 'ion', 0xf43c),          # ion-ios-gear-outline
    ('errorOutline', 'material', 0xf025),  # error_outline (outlined)
    ('fileOutline', 'material', 0xf12d),   # insert_drive_file (outlined)
]


def glyph_path(font, codepoint):
    cmap = font.getBestCmap()
    gname = cmap[codepoint]
    gs = font.getGlyphSet()
    bp = BoundsPen(gs)
    gs[gname].draw(bp)
    x0, y0, x1, y1 = bp.bounds
    pen = SVGPathPen(gs, ntos=lambda v: ('%.1f' % v).rstrip('0').rstrip('.'))
    # flip y and move the ink box to the origin
    tp = TransformPen(pen, (1, 0, 0, -1, -x0, y1))
    gs[gname].draw(tp)
    return pen.getCommands(), x1 - x0, y1 - y0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--fa', required=True)
    ap.add_argument('--ion', required=True)
    ap.add_argument('--material', required=True)
    ap.add_argument('--out', required=True)
    args = ap.parse_args()
    fonts = {'fa': TTFont(args.fa), 'ion': TTFont(args.ion), 'material': TTFont(args.material)}
    lines = [
        '// GENERATED by tool/art/extract_glyphs.py - do not edit by hand.',
        '//',
        '// Outlines from Font Awesome 4.7 (SIL OFL 1.1), Ionicons 2.0.1 (MIT) and',
        '// Material Icons (Apache 2.0); see THIRD_PARTY_NOTICES.md.',
        '',
        "import 'glyph.dart';",
        '',
        'abstract final class GlyphData {',
    ]
    for name, key, cp in GLYPHS:
        d, w, h = glyph_path(fonts[key], cp)
        lines.append('  static const %s = Glyph(%.1f, %.1f,' % (name, w, h))
        # split long path strings for readability
        chunks = [d[i:i + 90] for i in range(0, len(d), 90)]
        for i, c in enumerate(chunks):
            end = ');' if i == len(chunks) - 1 else ''
            lines.append("      '%s'%s" % (c, end))
    lines.append('}')
    with open(args.out, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
